name: internal-testing
protection_rules:
  - type: required_reviewers
    required_reviewers:
      - users: ["your-username"]  # Replace with actual GitHub username
  - type: wait_timer
    wait_timer: 0
deployment_branch_policy:
  protected_branches: false
  custom_branch_policies: true
  custom_branches: ["main"]