name: 🚀 Bypass Wrapper Build

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6.3
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Debug environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in root:"
        ls -la
        echo "Settings file content:"
        cat settings.gradle
        echo "Gradle version:"
        gradle --version
        
    - name: Build with gradle directly
      run: |
        gradle clean assembleDebug --no-daemon --stacktrace
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: nft-pro-debug
        path: app/build/outputs/apk/debug/app-debug.apk