name: 🚀 Direct Build

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Initialize Gradle wrapper
      run: |
        echo "Checking Gradle setup..."
        ls -la gradle/wrapper/
        echo "Settings file content:"
        cat settings.gradle.kts
        echo "Root build file:"  
        head -20 build.gradle.kts
        
    - name: Clean and build
      run: |
        ./gradlew clean --no-daemon --stacktrace
        ./gradlew assembleDebug --no-daemon --stacktrace
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: nft-pro-debug
        path: app/build/outputs/apk/debug/app-debug.apk